/*
 * main_servo.c
 *
 *  Created on: dec 04, 2025
 *      Author: Bruno
 *      Instituto Federal de Santa Catarina
 * 
 * Servo Motor implementation
 */
#include "../_core/hardware.h"
#include "../gpio/gpio.h"
#include "../_core/utils.h"

int main(void) {
    while (1) {
    
    //  For printing the value of the signal generated by the buttons
    //  SEGMENTS_BASE_ADDRESS = IRDA_BASE_ADDRESS
    
        // Case for each button of the controller
        SERVO_BASE_ADDRESS = 10;
        delay_(10000); 
        SERVO_BASE_ADDRESS = 20;
        delay_(10000); 
        SERVO_BASE_ADDRESS = 30;
	delay_(10000); 
    }
    return 0;
}

