/*
 * main_irda.c
 *
 *  Created on: Jul 22, 2025
 *      Author: Guido Momm & Conrado Becker Gressler 
 *      Instituto Federal de Santa Catarina
 * 
 * IRDA sensor implementation
 */
#include "../_core/hardware.h"
#include "../gpio/gpio.h"
#include "../_core/utils.h"

int main(void) {
    while (1) {
    
    //  For printing the value of the signal generated by the buttons
    //  SEGMENTS_BASE_ADDRESS = IRDA_BASE_ADDRESS
    
        // Case for each button of the controller
        switch ((IRDA_BASE_ADDRESS >> 24)) {
            case 0xFF:
                SEGMENTS_BASE_ADDRESS = 0x00;
                break;
            case 0xFE:
                SEGMENTS_BASE_ADDRESS = 0x01;
                break;
            case 0xFD:
                SEGMENTS_BASE_ADDRESS = 0x02;
                break;
            case 0xFC:
                SEGMENTS_BASE_ADDRESS = 0x03;
                break;
            case 0xFB:
                SEGMENTS_BASE_ADDRESS = 0x04;
                break;
            case 0xFA:
                SEGMENTS_BASE_ADDRESS = 0x05;
                break;
            case 0xF9:
                SEGMENTS_BASE_ADDRESS = 0x06;
                break;
            case 0xF8:
                SEGMENTS_BASE_ADDRESS = 0x07;
                break;
            case 0xF7:
                SEGMENTS_BASE_ADDRESS = 0x08;
                break;
            case 0xF6:
                SEGMENTS_BASE_ADDRESS = 0x09;
                break;
            case 0xF5:
                SEGMENTS_BASE_ADDRESS = 0x0A;
                break;
            case 0xF4:
                SEGMENTS_BASE_ADDRESS = 0x0B;
                break;
            case 0xF3:
                SEGMENTS_BASE_ADDRESS = 0x0C;
                break;
            case 0xF2:
                SEGMENTS_BASE_ADDRESS = 0x0D;
                break;
            case 0xF1:
                SEGMENTS_BASE_ADDRESS = 0x0E;
                break;
            case 0xF0:
                SEGMENTS_BASE_ADDRESS = 0xF0DA;
                break;
            case 0xEF:
                SEGMENTS_BASE_ADDRESS = 0x0F;
                break;
            case 0xEE:
                SEGMENTS_BASE_ADDRESS = 0x10;
                break;
            case 0xED:
                SEGMENTS_BASE_ADDRESS = 0x11;
                break;
            case 0xEC:
                SEGMENTS_BASE_ADDRESS = 0x12;
                break;
            case 0xEB:
                SEGMENTS_BASE_ADDRESS = 0x13;
                break;
            case 0xEA:
                SEGMENTS_BASE_ADDRESS = 0x14;
                break;
            case 0xE9:
                SEGMENTS_BASE_ADDRESS = 0x15;
                break;
            case 0xE8:
                SEGMENTS_BASE_ADDRESS = 0x16;
                break;
            default:
                break;
        }
        delay_(10000);   
    }
    return 0;
}

